#!/usr/bin/env python3
"""Generate glyphs/braille.txt -- the whole U+2800..U+28FF block.

CLI spinners cycle through braille patterns, so partial coverage makes the
spinner jitter between this font and the fallback.  The block is perfectly
regular -- codepoint low byte IS the dot bitmask -- so all 256 are generated.

Layout: two dot columns (1..2 and 4..5) and four dot rows, each dot a 2x2
block with a one-pixel gap, which is the only arrangement that fits 8 dots
into 7x14 without them touching.
"""
COLS = {0: 0b0110000, 1: 0b0000110}          # left dots -> cols 1,2; right -> 4,5
BANDS = [(2, 3), (5, 6), (8, 9), (11, 12)]
# bit index -> (column, row band).  Dots 1-3 and 7 are the left column.
DOT = {0: (0, 0), 1: (0, 1), 2: (0, 2), 6: (0, 3),
       3: (1, 0), 4: (1, 1), 5: (1, 2), 7: (1, 3)}

with open('glyphs/braille.txt', 'w') as fh:
    fh.write('# GENERATED by tools/gen-braille.py -- the whole U+2800 block.\n'
             '# The low byte of the codepoint is the dot bitmask, so nothing\n'
             '# here is a judgement call; regenerate rather than hand-edit.\n\n')
    for n in range(256):
        rows = [0] * 14
        for bit, (col, band) in DOT.items():
            if n & (1 << bit):
                for r in range(*BANDS[band]):
                    rows[r] |= COLS[col]
                rows[BANDS[band][1]] |= COLS[col]
        art = ['' .join('#' if v & (1 << (6 - c)) else '.' for c in range(7))
               for v in rows]
        fh.write(f'CHAR U+{0x2800 + n:04X} BRAILLE PATTERN {n:02X}\n'
                 + '\n'.join(art) + '\n\n')
print('glyphs/braille.txt: 256 patterns')
