#!/usr/bin/env python3
"""Generate the circled-digit dingbats, U+2776..U+2793.

Three runs of ten live in that range and Unicode separates them by a
distinction -- serif versus sans-serif -- that seven pixels cannot carry, so
U+2776..U+277F and U+278A..U+2793 come out identical here.  Both are the
NEGATIVE runs: a white digit knocked out of a black disc.  U+2780..U+2789 is
the positive run: a black digit inside a white ring.

U+2789 CIRCLED SANS-SERIF NUMBER TEN is NOT emitted.  Two digits need five
columns (a 3-wide zero, a 1-wide one and a gap) and the ring needs the two
outer columns, which leaves no separation at all: the one merges into the
left wall and the zero into the right.  The negative tens do not have that
problem -- a solid disc has no thin wall to merge with -- so those two ARE
emitted.

Writes glyphs/circled-digits.txt.  Hand-edit freely, but re-running this
overwrites the file.
"""
CELL_W, CELL_H = 7, 14
TOP = 3                      # the ring spans rows 3..11
BLANK = '.' * CELL_W

RING = ['..###..', '.#...#.', '#.....#', '#.....#', '#.....#',
        '#.....#', '#.....#', '.#...#.', '..###..']
DISC = ['..###..', '.#####.', '#######', '#######', '#######',
        '#######', '#######', '.#####.', '..###..']

# 3 wide, 5 tall -- the largest that leaves a clear column beside the ring.
DIGIT = {
    '1': ['.#.', '##.', '.#.', '.#.', '###'],
    '2': ['###', '..#', '###', '#..', '###'],
    '3': ['###', '..#', '###', '..#', '###'],
    '4': ['#.#', '#.#', '###', '..#', '..#'],
    '5': ['###', '#..', '###', '..#', '###'],
    '6': ['###', '#..', '###', '#.#', '###'],
    '7': ['###', '..#', '..#', '..#', '..#'],
    '8': ['###', '#.#', '###', '#.#', '###'],
    '9': ['###', '#.#', '###', '..#', '###'],
}
# 5 wide -- only ever knocked out of a disc, never set inside a ring.
TEN = ['.#.###.', '.#.#.#.', '.#.#.#.', '.#.#.#.', '.#.###.']

NAMES = ['ONE', 'TWO', 'THREE', 'FOUR', 'FIVE',
         'SIX', 'SEVEN', 'EIGHT', 'NINE', 'TEN']


def compose(base, art, col, negative):
    """Draw art onto a copy of base at column col; negative knocks it out."""
    rows = [list(r) for r in base]
    for i, line in enumerate(art):
        for j, ch in enumerate(line):
            if ch == '#':
                rows[2 + i][col + j] = '.' if negative else '#'
    return [''.join(r) for r in rows]


def cell(rows):
    art = [BLANK] * CELL_H
    for i, r in enumerate(rows):
        art[TOP + i] = r
    return '\n'.join(art)


def emit(out, cp, name, rows):
    out.append('CHAR U+%04X %s\n%s\n\n' % (cp, name, cell(rows)))


out = ['# GENERATED by tools/gen-circled-digits.py -- see that file for why\n'
       '# U+2789 is absent and why the two negative runs are identical.\n'
       '# Hand-edit freely, but re-running the generator overwrites it.\n\n']

for base_cp, prefix, negative in [
        (0x2776, 'DINGBAT NEGATIVE CIRCLED ', True),
        (0x2780, 'DINGBAT CIRCLED SANS-SERIF ', False),
        (0x278A, 'DINGBAT NEGATIVE CIRCLED SANS-SERIF ', True)]:
    for i, word in enumerate(NAMES):
        cp = base_cp + i
        kind = 'NUMBER ' if word == 'TEN' else 'DIGIT '
        name = prefix + kind + word
        if word == 'TEN':
            if not negative:
                continue                     # see the module docstring
            emit(out, cp, name, compose(DISC, TEN, 0, True))
        else:
            base = DISC if negative else RING
            emit(out, cp, name, compose(base, DIGIT[str(i + 1)], 2, negative))

open('glyphs/circled-digits.txt', 'w').write(''.join(out))
print('glyphs/circled-digits.txt:', sum(1 for s in out if s.startswith('CHAR')),
      'glyphs')
