#!/usr/bin/env python3
"""Regenerate docs/coverage.md -- what each size and face actually carries.

Usage: glyph-index.py [--out FILE] [SIZE ...]

Ragged coverage is a first-class state: a size with zero drawings still builds,
and comes out as plain upstream Tamzen.  This table is what turns that from a
wall into a queue -- someone who cares about 6x12 can see how far it has got
and go fill it in.

"missing" is measured against the union of every codepoint any size covers, so
the fullest size defines the target and no list has to be maintained by hand.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import glyphstore as gs


def main():
    argv = sys.argv[1:]
    out = os.path.join('docs', 'coverage.md')
    if argv and argv[0] == '--out':
        out, argv = argv[1], argv[2:]
    sizes = argv or sorted(d for d in os.listdir(gs.HAND_ROOT)
                           if os.path.isdir(os.path.join(gs.HAND_ROOT, d)))

    table = {}
    for size in sizes:
        for face in gs.FACES:
            table[size, face] = gs.resolve(size, face)
    target = set().union(*(set(v) for v in table.values())) if table else set()

    lines = ['# Coverage', '',
             'Generated by `make index`; do not edit.', '',
             f'Target set: {len(target)} codepoints, the union of everything '
             f'any size covers.', '',
             '| size | face | total | drawn here | upstream | generated | missing |',
             '|---|---|---:|---:|---:|---:|---:|']
    for size in sizes:
        for face in gs.FACES:
            r = table[size, face]
            c = {'hand': 0, 'upstream': 0, 'gen': 0}
            for layer, _bm in r.values():
                c[layer] += 1
            lines.append(f'| {size} | {face} | {len(r)} | {c["hand"]} | '
                         f'{c["upstream"]} | {c["gen"]} | '
                         f'{len(target - set(r))} |')
    lines.append('')
    text = '\n'.join(lines)
    os.makedirs(os.path.dirname(out) or '.', exist_ok=True)
    open(out, 'w', encoding='utf-8').write(text)
    print(text)


main()
